[package]
name = "update-ssh-keys"
version = "0.1.0"
authors = ["Stephen Demos <stephen.demos@coreos.com>"]

[dependencies]
error-chain = "0.10"
users = "0.5"
clap = "2.26"
openssh-keys = "0.1"
fs2 = "0.4"

[profile.release]
lto = true
panic = 'abort'
